# Generated by Django 4.1.3 on 2022-12-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='telefono',
            new_name='tele',
        ),
    ]
