# Generated by Django 4.1.3 on 2022-12-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_telefono_persona_tele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tele',
            field=models.CharField(max_length=50),
        ),
    ]
